#spring:
#  application:
#    name: productsapp
#  datasource:
#    url: jdbc:mysql://localhost:3306/productsapp
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: update

spring:
  application:
    name: productsapp
  datasource:
    url: jdbc:h2:mem:productsappv2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto:update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]